import type { Metadata } from "next";

export const metadata: Metadata = {
    title:"HOME - next TS",
    description: " Generated by create next app",
};

export default function HomeLayout({
    children, 
}: Readonly<{
    children: React.ReactNode;
}>) {
    return(
        <main>
            <div 
            className="home"
            style={{
                padding: 20,
                background: "grey",
            }}>
                {children}
            </div>
        </main>
    )
}